# Basic Numpy Operations


In [5]:
import numpy as np

a = np.arange(20, 30)
b = np.arange(10, 20)
print("a:\n", a, "\nb:\n", b)
c = a-b
print("a - b:\n", c)

print("b**2:\n", b**2)

d = 10 * np.sin(a)
print("d:\n", d)

print(a < 25)

a:
 [20 21 22 23 24 25 26 27 28 29] 
b:
 [10 11 12 13 14 15 16 17 18 19]
a - b:
 [10 10 10 10 10 10 10 10 10 10]
b**2:
 [100 121 144 169 196 225 256 289 324 361]
d:
 [ 9.12945251  8.36655639 -0.08851309 -8.46220404 -9.05578362 -1.3235175
  7.6255845   9.56375928  2.70905788 -6.63633884]
[ True  True  True  True  True False False False False False]
