# Quickstart

## The Basics

In [4]:
#getting started
import numpy as np

a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
a = a.reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
print(a.ndim)

2


In [9]:
print(a.size)

15


In [10]:
print(a.dtype)

int64


In [11]:
print(a.itemsize)

8


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(a.reshape(5, 3))

print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
#creating numpy arrays from list
b = np.array([1, 5, 2 , 7 , 8])
print(b)
print(type(b))

[1 5 2 7 8]
<class 'numpy.ndarray'>


In [17]:
_a = a.reshape(5, 3)
print(id(a))
print(id(_a))

140405301646720
140405301649200


In [18]:
print(a)
print(_a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [19]:
print(a.shape)

(3, 5)


In [20]:
#create a numpy array from tuple
c = np.array((1, 4, 2, 5 ,65,7 , 7, 6))
print(c, type(c))

[ 1  4  2  5 65  7  7  6] <class 'numpy.ndarray'>


In [22]:
#specifying datatypes
d = np.array([(1, 3, 6, 8), (5, 6, 8, 10)], dtype=complex)
print(d, type(d))

[[  1.+0.j   3.+0.j   6.+0.j   8.+0.j]
 [  5.+0.j   6.+0.j   8.+0.j  10.+0.j]] <class 'numpy.ndarray'>


In [25]:
# ones and zeros

z = np.zeros((4, 5), dtype=np.int8)
print(z, type(z))

o = np.ones((5, 6), dtype=np.int8)
print(o, type(o))

#creating arrays without initializng
e = np.empty((3, 3))
print(e, type(e))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] <class 'numpy.ndarray'>
[[  6.93696558e-310   1.92703230e-316   6.93701644e-310]
 [  9.05633755e-043   1.37298862e-071   2.51383884e-071]
 [  5.05232117e-038   6.93696650e-310   3.95252517e-322]] <class 'numpy.ndarray'>


In [26]:
#creating a sequence of numbers
seq = np.arange(20)
print(seq)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
#sequence with start and stop
seqA = np.arange(5, 30)
print(seqA)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [31]:
#with an interval
seqB = np.arange(5, 30, 3)
print(seqB)
seqB = np.arange(0, 5, 0.3)
print(seqB)

[ 5  8 11 14 17 20 23 26 29]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9  4.2
  4.5  4.8]


In [30]:
# when we use np.arange(), it's hard to predict the array size.
# so, we use np.linspace() to overcome this problem
seqC = np.linspace(0, 5, 15)
print(seqC)

[ 0.          0.35714286  0.71428571  1.07142857  1.42857143  1.78571429
  2.14285714  2.5         2.85714286  3.21428571  3.57142857  3.92857143
  4.28571429  4.64285714  5.        ]


In [33]:
x = np.linspace(0, 2*np.pi, 100)
print(x)
f = np.sin(x)
print(f)

[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88692191
  4.95038842  5.01385494  5.07732146  5.14078798  5.2

In [45]:
zx = np.arange(10000).reshape(100, 100)
print(zx)


np.set_printoptions(threshold=200000)
print(zx)

TypeError: '>' not supported between instances of 'int' and 'str'