## Universal Functions

In [3]:
import numpy as np
B = np.arange(3)
print(B)

[0 1 2]


In [4]:
expB = np.exp(B)
print(expB)

[ 1.          2.71828183  7.3890561 ]


In [5]:
sqrtB = np.sqrt(B)
print(sqrtB)

[ 0.          1.          1.41421356]


In [9]:
C = np.linspace(8, 7.98, 3)
print(B)
print(C)
sumBC = np.add(B, C)
print(sumBC)

[0 1 2]
[ 8.    7.99  7.98]
[ 8.    8.99  9.98]
